name: py310
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bottleneck=1.4.2=py310hbda83bc_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - et_xmlfile=1.1.0=py310hca03da5_0
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - ncurses=6.4=h313beb8_0
  - numexpr=2.10.1=py310h5d9532f_0
  - numpy=2.2.2=py310h3b2db8e_0
  - numpy-base=2.2.2=py310ha9811e2_0
  - openpyxl=3.1.5=py310h80987f9_0
  - openssl=3.0.15=h80987f9_0
  - pandas=2.2.3=py310hcf29cfe_0
  - pip=25.0=py310hca03da5_0
  - python=3.10.16=hb885b13_1
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - readline=8.2=h1a28f6b_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - albucore==0.0.13
      - albumentations==1.4.10
      - annotated-types==0.7.0
      - anyio==4.8.0
      - asgiref==3.8.1
      - astor==0.8.1
      - beautifulsoup4==4.13.3
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - cobble==0.1.4
      - contourpy==1.3.1
      - cryptography==43.0.3
      - cycler==0.12.1
      - cython==3.0.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diff-match-patch==20241021
      - distro==1.9.0
      - django==4.2.16
      - django-ckeditor-5==0.2.17
      - django-cors-headers==4.7.0
      - django-environ==0.12.0
      - django-formtools==2.4.1
      - django-import-export==3.3.1
      - django-jazzmin==3.0.1
      - django-js-asset==3.0.1
      - django-ranged-response==0.2.0
      - django-simple-captcha==0.6.1
      - django-utils-six==2.0
      - django-xadmin==0.5.0
      - djangorestframework==3.15.2
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - fire==0.7.0
      - fonttools==4.56.0
      - future==0.18.3
      - google==3.0.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httplib2==0.9.2
      - httpx==0.28.1
      - idna==3.10
      - imageio==2.37.0
      - imgaug==0.4.0
      - iniconfig==2.0.0
      - jiter==0.8.2
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lmdb==1.6.2
      - lxml==5.3.1
      - mammoth==1.9.0
      - markuppy==1.17
      - matplotlib==3.10.0
      - mysqlclient==2.2.7
      - networkx==3.4.2
      - odfpy==1.4.1
      - openai==1.63.2
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.3.0
      - packaging==24.2
      - paddleocr==2.9.1
      - paddlepaddle==2.6.2
      - pillow==11.1.0
      - pluggy==1.5.0
      - protobuf==5.29.3
      - py==1.11.0
      - pyclipper==1.3.0.post6
      - pycparser==2.22
      - pycryptodome==3.9.9
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pymysql==1.1.1
      - pyparsing==3.2.1
      - pytesseract==0.3.13
      - pytest==8.0.0
      - pytest-django==4.8.0
      - python-docx==1.1.2
      - python-magic==0.4.27
      - pytz==2020.5
      - pyyaml==6.0.2
      - rapidfuzz==3.12.1
      - requests==2.31.0
      - retry==0.9.2
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - setuptools==76.0.0
      - shapely==2.0.7
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlparse==0.5.3
      - tablib==3.5.0
      - tabulate==0.9.0
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2025.2.18
      - tomli==2.2.1
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - volcengine==1.0.174
      - volcengine-python-sdk==1.0.125
      - xlrd==1.2.0
      - xlwt==1.3.0
prefix: /Users/linyuan/anaconda3/envs/py310
