[tool.black]
line-length = 100
target-version = ["py313"]
include = '\\.pyi?$'
exclude = '''
/(
  \.git
  | \.venv
  | env
  | venv
  | build
  | dist
  | migrations
  | static
  | staticfiles
  | media
  | docs/vendor
)/
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_first_party = ["grading", "hualiEdu"]
skip = ["migrations", "static", "staticfiles", "media"]

[tool.flake8]
max-line-length = 120
select = ["E9", "F63", "F7", "F82"]
extend-ignore = ["E203", "W503", "E501"]
exclude = ["migrations", "static", "staticfiles", "media", "docs"]
